/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bfc8cd",
        "on-secondary-fixed": "#0f1e23",
        "surface-dim": "#d8dadd",
        "on-tertiary-container": "#94e7d5",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#b9c9d0",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#d2e2e9",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#00201b",
        "primary": "#004d64",
        "primary-fixed-dim": "#87d0f2",
        "on-primary-container": "#a2e1ff",
        "tertiary-fixed": "#9ff2e0",
        "on-secondary-container": "#56656b",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8eb",
        "inverse-surface": "#2d3133",
        "background": "#f7f9fc",
        "tertiary-fixed-dim": "#83d6c4",
        "on-surface-variant": "#3f484d",
        "on-primary-fixed": "#001f2a",
        "surface-tint": "#016684",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005046",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#006684",
        "error": "#ba1a1a",
        "surface": "#f7f9fc",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#d5e5ec",
        "surface-container": "#eceef1",
        "primary-fixed": "#bee9ff",
        "tertiary-container": "#006a5c",
        "secondary": "#526167",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#004d64",
        "surface-bright": "#f7f9fc",
        "on-background": "#181c1e",
        "on-surface": "#181c1e",
        "outline": "#70787e",
        "tertiary": "#005045",
        "inverse-primary": "#87d0f2",
        "on-secondary-fixed-variant": "#3a494f",
        "on-primary-container-custom": "#a2e1ff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
